language: rust
cache: cargo
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  # rest of your existing "before_cache"

rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
    - cargo build --verbose --all
    - cargo test --verbose --all
