name: Base CI/CD Pipeline

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        working-directory: ./radishmq
        run: cargo build --release

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Format check
        working-directory: ./radishmq
        run: cargo fmt -- --check
      - name: Clippy
        working-directory: ./radishmq
        run: cargo clippy -- -D warnings

